include:
  - starter-kit-storage-and-interfaces/docker-compose-demo.yml
  - starter-kit-htsget/docker-compose.yml

services:
  beacon:
    image: harbor.nbis.se/test/ejprd-gdi-beacon:1
    depends_on:
      db:
        condition: service_healthy
    working_dir: '/beacon'
    entrypoint: ['python', '-m', 'beacon']
    volumes:
      - ./config/beacon_conf.py:/beacon/beacon/conf.py
      - ./config/datasets.yml:/beacon/beacon/request/datasets.yml
      - ./config/cohorts.yml:/beacon/beacon/request/cohorts.yml
      - ./config/public_datasets.yml:/beacon/permissions/public_datasets.yml
      - ./config/beacon.env:/beacon/permissions/permissions-ui/.env

  db:
    image: mongo:5
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: beacon
    healthcheck:
      test: ["CMD", "sh", "-c", "[ -f /var/log/mongodb/mongoinitialized ] || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./config/mongoinit/:/docker-entrypoint-initdb.d/:ro
      - ../../data/beaconized/:/data
