services:
  # fdp-client:
  #   image: fairdata/fairdatapoint:1.17.1
  #   restart: always
  #   env_file:
  #     - ./fdp_env
  #   entrypoint: 
  #     - java
  #     - -jar
  #     - app.jar 
  #     - --spring.profiles.active=production
  #     - --spring.config.location=classpath:/application.yml,file:/fdp/application-production.yml
  #   healthcheck:
  #     test: curl --fail --silent localhost:80/actuator/health | grep UP || exit 1
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s
  #   environment:
  #     - FDP_MONGO_HOST=mongo
  #     - FDP_MONGO_USER=root
  #     - FDP_MONGO_PASS=password
  #     - FDP_MONGO_PORT=27017
  #     - FDP_MONGO_DB=fdp
  #     - FDP_TRIPLE_STORE_TYPE=4
  #     - FDP_TRIPLE_STORE_URL=http://graphdb:7200
  #     - FDP_TRIPLE_STORE_REPOSITORY=fdp
  #     - FDP_TRIPLE_STORE_USERNAME=fdp
  #     - FDP_TRIPLE_STORE_PASSWORD=topsecret
  #   depends_on:
  #     mongo:
  #       condition: service_healthy
  #     graphdb:
  #       condition: service_healthy
  #   configs:
  #     - source: fdp-application.yml
  #       target: /fdp/application-production.yml
  # https://github.com/FAIRDataTeam/FAIRDataPoint/blob/38a5fbdf3bc988447beda2c5daaa1938f15e5408/src/main/resources/application.yml
  # fdp_index_client:
  #   image: fairdata/fairdatapoint-client:1.17.0
  #   restart: always
  #   environment:
  #     FDP_HOST: fdp
  #     APP: fairdatapoint-index
  #   configs:
  #     - source: variables.scss
  #       target: /src/scss/custom/_variables.scss
  #     - source: logo.png
  #       target: /usr/share/nginx/html/assets/logo.png
  #     - source: favicon.ico
  #       target: /usr/share/nginx/html/favicon.ico
  #   depends_on:
  #     fdp:
  #       condition: service_healthy


  # fdp_index_client:
  #   ports: 
  #     - 7075:80
  #   networks: 
  #     - fdp-default
  #     - graphdb-setup
  #     - resource-metadata-internal

networks:
  graphdb-setup:
    # driver: overlay
    # internal: true
  resource-metadata-internal:
    internal: true
  care-sm-data-internal:
    internal: true
  all-authenticated-users:
    internal: true
  public:
  fdp-default:
    name: ${PREFIX}-default
