services:
  graphdb:
    ports: 
      - ${GDB_PORT}:7200
    networks: 
      - graphdb-setup
      - resource-metadata-internal
      - care-sm-data-internal

  fdp:
    ports: 
      - 7080:80
    networks: 
      - fdp-default
      - graphdb-setup
      - resource-metadata-internal
    environment:
      - FDP_CLIENT_URL=http://localhost:${FDP_PORT}
      - FDP_PERSISTENT_URL=http://localhost:${FDP_PORT}

  fdp_client:
    ports: 
      - ${FDP_PORT}:80
    networks: 
      - fdp-default
      - graphdb-setup
      - resource-metadata-internal

  mongo:
      networks: 
      - fdp-default
      - resource-metadata-internal
 
  beacon_count:
    ports:
      - ${BEACON_PORT}:8000
    networks:
      - fdp-default
      - care-sm-data-internal

networks:
  graphdb-setup:
    internal: true
  resource-metadata-internal:
    internal: true
  care-sm-data-internal:
    internal: true
  all-authenticated-users:
    internal: true
  public:
  fdp-default:

