services:
  graphdb:
    ports: 
      - ${GDB_EXPOSED_PORT}:7200
    networks: 
      - graphdb-setup
      - resource-metadata-internal
      - care-sm-data-internal

  fdp:
    networks: 
      - fdp-default
      - graphdb-setup
      - resource-metadata-internal
    environment:
      - FDP_CLIENT_URL=http://localhost:${FDP_EXPOSED_PORT}
      - FDP_PERSISTENT_URL=http://localhost:${FDP_EXPOSED_PORT}

  fdp_client:
    ports: 
      - ${FDP_EXPOSED_PORT}:80
    networks: 
      - fdp-default
      - graphdb-setup
      - resource-metadata-internal

  mongo:
      networks: 
      - fdp-default
      - resource-metadata-internal
 
  beacon_count:
    ports:
      - ${BEACON_EXPOSED_PORT}:8000
    networks:
      - fdp-default
      - care-sm-data-internal

networks:
  graphdb-setup:
    internal: true
  resource-metadata-internal:
    # internal: true
    name: ejprd-secure
    external: true
  care-sm-data-internal:
    # internal: true
    name: ejprd-secure
    external: true
  fdp-default:

  public:
    name: ejprd-public
    external: true
  secure:
    name: ejprd-secure
    external: true
