services:
  graphdb-setup:
    image: ontotext/graphdb:10.6.1
    restart: no
    entrypoint: /bin/bash /tmp/config/set-up-db.sh
    volumes:
      - graphdb:/opt/graphdb/home
      - graphdb-config:/tmp/config/:ro

  graphdb:
    image: ontotext/graphdb:10.6.1
    restart: always
    healthcheck:
      test: wget -O /dev/null -q http://localhost:7200/protocol || exit 1
      interval: ${HEALTHCHECK_INTERVAL:-1m}
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      graphdb-setup:
        condition: service_completed_successfully
    volumes:
      - graphdb:/opt/graphdb/home

  fdp:
    image: fairdata/fairdatapoint:1.17.1
    restart: always
    env_file:
      - ./fdp_env
    entrypoint: 
      - java
      - -jar
      - app.jar 
      - --spring.profiles.active=production
      - --spring.config.location=classpath:/application.yml,file:/fdp/application-production.yml
    healthcheck:
      test: curl --fail --silent localhost:80/actuator/health | grep UP || exit 1
      interval: ${HEALTHCHECK_INTERVAL:-1m}
      timeout: 5s
      retries: 5
      start_period: 40s
    environment:
      - FDP_MONGO_HOST=${FDP_MONGO_HOST}
      - FDP_MONGO_USER=${FDP_MONGO_USER}
      - FDP_MONGO_PASS=${FDP_MONGO_PASS}
      - FDP_MONGO_PORT=${FDP_MONGO_PORT}
      - FDP_MONGO_DB=${FDP_MONGO_DB}
      - FDP_TRIPLE_STORE_TYPE=4
      - FDP_TRIPLE_STORE_URL=${FDP_GraphDB_Url}
      - FDP_TRIPLE_STORE_REPOSITORY=${FDP_GraphDB_Repo}
      - FDP_TRIPLE_STORE_USERNAME=${FDP_GraphDB_User}
      - FDP_TRIPLE_STORE_PASSWORD=${FDP_GraphDB_Pass}
    depends_on:
      mongo:
        condition: service_healthy
      graphdb:
        condition: service_healthy
    configs:
      - source: fdp-application.yml
        target: /fdp/application-production.yml

  fdp_client:
    hostname: fdpclient
    image: fairdata/fairdatapoint-client:1.16.3
    restart: always
    environment:
      FDP_HOST: fdp
    configs:
      - source: variables.scss
        target: /src/scss/custom/_variables.scss
      - source: logo.png
        target: /usr/share/nginx/html/assets/logo.png
      - source: favicon.ico
        target: /usr/share/nginx/html/favicon.ico
    depends_on:
      fdp:
        condition: service_healthy

  mongo:
    image: mongo:4.2.3
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${FDP_MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${FDP_MONGO_PASS}
    healthcheck:
      test: mongo --eval 'db.runCommand("ping").ok' localhost:${FDP_MONGO_PORT}/test --quiet || exit 1
      interval: ${HEALTHCHECK_INTERVAL:-1m}
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

  beacon_count:
    image: pabloalarconm/beacon-api4care-sm:0.2.0
    # https://github.com/CARE-SM/beaconAPI4CARESM
    restart: always
    environment:
      - TRIPLESTORE_URL=${BEACON_TRIPLESTORE_URL}
      - TRIPLESTORE_USERNAME=${BEACON_TRIPLESTORE_USERNAME}
      - TRIPLESTORE_PASSWORD=${BEACON_TRIPLESTORE_PASSWORD}
      - FILTER_SEX=True
      - FILTER_DISEASE=True
      - FILTER_SYMPTOM=True
      - FILTER_GENE_VARIANT=True
      - FILTER_BIRTHYEAR=True
      - FILTER_AGE_SYMPTOM_ONSET=True
      - FILTER_AGE_DIAGNOSIS=True
      - URL_SERVER=http://beacon/beaconAPI/  # DO NOT include the path e.g. /individuals
    depends_on:
      graphdb:
        condition: service_healthy

volumes: 
  graphdb:
  graphdb-config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./graphdb/
  mongo-data: 
  mongo-configdb:

configs:
  favicon.ico:
    file: ./fdp-client/favicon.ico
  logo.png:
    file: ./fdp-client/assets/logo.png
  variables.scss:
    file: ./fdp-client/variables.scss
  fdp-application.yml:
    file: ./fdp-application.yml